from datetime import datetime

from dcim.models import Device
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_datetime
from netbox.api.viewsets import NetBoxModelViewSet
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from ..choices import ComplianceResultStatusChoices
from ..models import (
    ComplianceExemption,
    ComplianceMeasure,
    CompliancePackage,
    ComplianceResult,
    ComplianceSnapshot,
    MeasureAssignment,
    PackageAssignment,
    PackageMeasure,
)
from ..services import build_snapshot_data, get_effective_measures, score_device
from . import serializers
from .. import filtersets

__all__ = (
    'ComplianceMeasureViewSet',
    'CompliancePackageViewSet',
    'PackageMeasureViewSet',
    'PackageAssignmentViewSet',
    'MeasureAssignmentViewSet',
    'ComplianceExemptionViewSet',
    'ComplianceResultViewSet',
    'ComplianceSnapshotViewSet',
    'BulkResultIngestView',
    'DeviceComplianceStatusView',
    'MonthlyReportView',
)


class ComplianceMeasureViewSet(NetBoxModelViewSet):
    queryset = ComplianceMeasure.objects.all()
    serializer_class = serializers.ComplianceMeasureSerializer
    filterset_class = filtersets.ComplianceMeasureFilterSet


class CompliancePackageViewSet(NetBoxModelViewSet):
    queryset = CompliancePackage.objects.prefetch_related('measures')
    serializer_class = serializers.CompliancePackageSerializer
    filterset_class = filtersets.CompliancePackageFilterSet


class PackageMeasureViewSet(NetBoxModelViewSet):
    queryset = PackageMeasure.objects.select_related('package', 'measure')
    serializer_class = serializers.PackageMeasureSerializer
    filterset_class = filtersets.PackageMeasureFilterSet


class PackageAssignmentViewSet(NetBoxModelViewSet):
    queryset = PackageAssignment.objects.select_related(
        'package', 'device', 'device_role', 'site', 'site_group', 'platform', 'tag',
    )
    serializer_class = serializers.PackageAssignmentSerializer
    filterset_class = filtersets.PackageAssignmentFilterSet


class MeasureAssignmentViewSet(NetBoxModelViewSet):
    queryset = MeasureAssignment.objects.select_related('device', 'measure')
    serializer_class = serializers.MeasureAssignmentSerializer
    filterset_class = filtersets.MeasureAssignmentFilterSet


class ComplianceExemptionViewSet(NetBoxModelViewSet):
    queryset = ComplianceExemption.objects.select_related('measure', 'device', 'site', 'site_group', 'tag')
    serializer_class = serializers.ComplianceExemptionSerializer
    filterset_class = filtersets.ComplianceExemptionFilterSet


class ComplianceResultViewSet(NetBoxModelViewSet):
    queryset = ComplianceResult.objects.select_related('device', 'measure')
    serializer_class = serializers.ComplianceResultSerializer
    filterset_class = filtersets.ComplianceResultFilterSet


class ComplianceSnapshotViewSet(NetBoxModelViewSet):
    """Read-only + delete: snapshots are generated by the monthly job/command, never created/edited via the API."""
    queryset = ComplianceSnapshot.objects.select_related('device')
    serializer_class = serializers.ComplianceSnapshotSerializer
    filterset_class = filtersets.ComplianceSnapshotFilterSet
    http_method_names = ['get', 'delete', 'head', 'options']


#
# Bulk result ingestion
#

def _resolve_device(batch):
    device_id = batch.get('device_id')
    if device_id is not None:
        return Device.objects.filter(pk=device_id).first()
    value = batch.get('device')
    if value is None:
        return None
    if isinstance(value, int):
        return Device.objects.filter(pk=value).first()
    return Device.objects.filter(name=value).first()


def _resolve_measure(value):
    if value is None:
        return None
    if isinstance(value, int):
        return ComplianceMeasure.objects.filter(pk=value).first()
    return ComplianceMeasure.objects.filter(slug=value).first()


def _parse_timestamp(value):
    if value is None:
        return None
    if isinstance(value, str):
        return parse_datetime(value)
    return value


class BulkResultIngestView(APIView):
    """
    POST /api/plugins/compliance/results/bulk/

    Accepts a single {"device": ..., "results": [...]} object, or a list of
    such objects to cover multiple devices in one call. Validates the whole
    payload before writing anything (atomic, no partial writes on error).
    """
    queryset = ComplianceResult.objects.all()

    def post(self, request):
        payload = request.data
        if isinstance(payload, dict):
            payload = [payload]
        if not isinstance(payload, list):
            return Response(
                {'detail': 'Payload must be an object or a list of objects.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        errors = []
        resolved_batches = []

        for batch_index, batch in enumerate(payload):
            device = _resolve_device(batch)
            if device is None:
                errors.append({
                    'index': batch_index,
                    'error': f"Unknown device: {batch.get('device') or batch.get('device_id')!r}",
                })
                continue

            source = batch.get('source', '')
            default_timestamp = _parse_timestamp(batch.get('timestamp'))
            if batch.get('timestamp') and default_timestamp is None:
                errors.append({'index': batch_index, 'error': f"Invalid timestamp: {batch.get('timestamp')!r}"})
                continue

            resolved_items = []
            for item_index, item in enumerate(batch.get('results', [])):
                measure = _resolve_measure(item.get('measure'))
                if measure is None:
                    errors.append({
                        'index': batch_index, 'item': item_index,
                        'error': f"Unknown measure: {item.get('measure')!r}",
                    })
                    continue

                item_status = item.get('status')
                if item_status not in ComplianceResultStatusChoices.values():
                    errors.append({
                        'index': batch_index, 'item': item_index,
                        'error': f"Invalid status: {item_status!r}",
                    })
                    continue

                if item.get('timestamp'):
                    timestamp = _parse_timestamp(item['timestamp'])
                    if timestamp is None:
                        errors.append({
                            'index': batch_index, 'item': item_index,
                            'error': f"Invalid timestamp: {item['timestamp']!r}",
                        })
                        continue
                else:
                    timestamp = default_timestamp

                resolved_items.append({
                    'measure': measure,
                    'status': item_status,
                    'details': item.get('details', {}),
                    'timestamp': timestamp,
                })

            resolved_batches.append({'device': device, 'source': source, 'items': resolved_items})

        if errors:
            return Response({'errors': errors}, status=status.HTTP_400_BAD_REQUEST)

        warnings = []
        created = 0
        with transaction.atomic():
            for batch in resolved_batches:
                device = batch['device']
                effective = get_effective_measures(device)
                effective_measure_ids = {row.measure.pk for rows in effective['packages'].values() for row in rows}
                effective_measure_ids |= {row.measure.pk for row in effective['direct']}

                for item in batch['items']:
                    if item['measure'].pk not in effective_measure_ids:
                        warnings.append(
                            f"{device}: measure '{item['measure'].slug}' is not currently in this "
                            f"device's effective measure set"
                        )
                    create_kwargs = {
                        'device': device,
                        'measure': item['measure'],
                        'status': item['status'],
                        'details': item['details'],
                        'source': batch['source'],
                    }
                    if item['timestamp'] is not None:
                        create_kwargs['timestamp'] = item['timestamp']
                    ComplianceResult.objects.create(**create_kwargs)
                    created += 1

        return Response({'created': created, 'warnings': warnings}, status=status.HTTP_201_CREATED)


class DeviceComplianceStatusView(APIView):
    """GET /api/plugins/compliance/devices/{id}/status/ -- live dashboard payload for one device."""
    queryset = Device.objects.all()

    def get(self, request, pk):
        device = get_object_or_404(Device, pk=pk)
        data, overall_score, compliant = build_snapshot_data(device)
        return Response({
            'device': device.pk,
            'device_name': device.name,
            'overall_score': overall_score,
            'compliant': compliant,
            **data,
        })


class MonthlyReportView(APIView):
    """GET /api/plugins/compliance/reports/{YYYY-MM}/ -- snapshot summary for a period."""
    queryset = ComplianceSnapshot.objects.all()

    def get(self, request, period):
        try:
            period_date = datetime.strptime(period, '%Y-%m').date().replace(day=1)
        except ValueError:
            return Response(
                {'detail': 'period must be in YYYY-MM format'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        qs = ComplianceSnapshot.objects.filter(period=period_date).select_related('device')

        site_id = request.query_params.get('site_id')
        role_id = request.query_params.get('role_id')
        tag_id = request.query_params.get('tag_id')
        if site_id:
            qs = qs.filter(device__site_id=site_id)
        if role_id:
            qs = qs.filter(device__role_id=role_id)
        if tag_id:
            qs = qs.filter(device__tags__id=tag_id)

        total = qs.count()
        compliant_count = qs.filter(compliant=True).count()
        serializer = serializers.ComplianceSnapshotSerializer(qs, many=True, context={'request': request})

        return Response({
            'period': period_date,
            'total': total,
            'compliant': compliant_count,
            'non_compliant': total - compliant_count,
            'devices': serializer.data,
        })
