# Generated by Django 6.0.6 on 2026-09-05 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0237_module_remove_local_context_data'),
        ('netbox_compliance', '0008_packageassignment_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSnapshotMeasureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('measure', models.CharField(db_index=True, max_length=100)),
                ('measure_name', models.CharField(max_length=200)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('package_name', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('required', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='compliancesnapshot',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_snapshots', to='dcim.devicerole'),
        ),
        migrations.AddField(
            model_name='compliancesnapshot',
            name='role_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compliancesnapshot',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_snapshots', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='compliancesnapshot',
            name='site_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compliancesnapshotmeasureresult',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_results', to='netbox_compliance.compliancesnapshot'),
        ),
        migrations.AddIndex(
            model_name='compliancesnapshotmeasureresult',
            index=models.Index(fields=['measure', 'status'], name='netbox_comp_measure_1a1579_idx'),
        ),
    ]
